<%@ Page Title="Przeglądaj pojazdy" Language="C#" MasterPageFile="~/Wzorcowa.Master" AutoEventWireup="true" CodeBehind="Przegladaj_pojazd.aspx.cs" Inherits="Aplikacja_dyplomowa.Przeglądaj.Przegladaj_pojazd" %>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>Numer rejestracyjny pojazdu:
        <br>
<asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="tablica_rejestracyjna" DataValueField="Id_nr_identyfikacyjny_autobusu">
</asp:DropDownList>
<br>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Numer_identyfikacyjny_autobusu]"></asp:SqlDataSource>
<asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT Marka.marka, Model.model, Numer_identyfikacyjny_autobusu.tablica_rejestracyjna, Rok_produkcji.rok_produkcji FROM Numer_identyfikacyjny_autobusu INNER JOIN Model ON Numer_identyfikacyjny_autobusu.id_model = Model.Id_model INNER JOIN Marka ON Model.id_marka = Marka.id_marka INNER JOIN Rok_produkcji ON Numer_identyfikacyjny_autobusu.Id_rok_produkcji = Rok_produkcji.Id_rok_produkcji

WHERE Numer_identyfikacyjny_autobusu.id_nr_identyfikacyjny_autobusu = @tablica_rejestracyjna">
    <SelectParameters>
        <asp:ControlParameter ControlID="DropDownList1" Name="tablica_rejestracyjna" PropertyName="SelectedValue" />
    </SelectParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" Font-Bold="True" Font-Names="Arial" Font-Size="Medium" ForeColor="#333333" GridLines="None" HorizontalAlign="Center" Width="900px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" EmptyDataText="Brak danych do wyświetlania." DataSourceID="SqlDataSource2">
        <AlternatingRowStyle BackColor="White" HorizontalAlign="Center" VerticalAlign="Middle" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="marka" HeaderText="Marka" SortExpression="marka" />
            <asp:BoundField DataField="model" HeaderText="Model" SortExpression="model" />
            <asp:BoundField DataField="tablica_rejestracyjna" HeaderText="Numer identyfikacyjny " SortExpression="tablica_rejestracyjna" />
            <asp:BoundField DataField="rok_produkcji" HeaderText="Rok produkcji" SortExpression="rok_produkcji" />
        </Columns>
        <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle HorizontalAlign="Center" VerticalAlign="Middle" BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView> 

    </div>
</asp:Content>
