<%@ Page Title="Przeglądaj naprawy" Language="C#" MasterPageFile="~/Wzorcowa.Master" AutoEventWireup="true" CodeBehind="Przegladaj_naprawy.aspx.cs" Inherits="Aplikacja_dyplomowa.Przeglądaj.Przegladaj_naprawy" %>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>Numer rejestracyjny pojazdu: 
        <br>
    <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="tablica_rejestracyjna" DataValueField="Id_nr_identyfikacyjny_autobusu">
    </asp:DropDownList>
        <br>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" Font-Bold="True" Font-Names="Arial" HorizontalAlign="Center" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="900px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" EmptyDataText="Brak danych do wyświetlania.">
        <AlternatingRowStyle BackColor="White" HorizontalAlign="Center" VerticalAlign="Middle" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="Id_nr_identyfikacyjny_autobusu" HeaderText="Id_nr_identyfikacyjny_autobusu" SortExpression="Id_nr_identyfikacyjny_autobusu" Visible="False" />
            <asp:BoundField DataField="naprawy_wyjscie" HeaderText="Rozpoczęcie naprawy" SortExpression="naprawy_wyjscie" />
            <asp:BoundField DataField="naprawy_powrot" HeaderText="Zakończenie naprawy" SortExpression="naprawy_powrot" />
        </Columns>
        <EditRowStyle BackColor="#999999" BorderColor="AliceBlue" />
        <FooterStyle BackColor="#5D7B9D" Font-Names="Arial" ForeColor="White" Font-Bold="True" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle HorizontalAlign="Center" VerticalAlign="Middle" BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" HorizontalAlign="Center" VerticalAlign="Middle" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Numer_identyfikacyjny_autobusu] ORDER BY [tablica_rejestracyjna]"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [Id_nr_identyfikacyjny_autobusu], [naprawy_wyjscie], [naprawy_powrot] FROM [Naprawy] WHERE ([Id_naprawy] = @Id_naprawy)">
        <SelectParameters>
            <asp:ControlParameter ControlID="DropDownList1" Name="Id_naprawy" PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>
    </asp:SqlDataSource>
        </div>
</asp:Content>
