<%@ Page Title="Przeglądaj pracowników" Language="C#" MasterPageFile="~/Wzorcowa.Master" AutoEventWireup="true" CodeBehind="Przegladaj_pracownikow.aspx.cs" Inherits="Aplikacja_dyplomowa.Przeglądaj.Przegladaj_pracownikow" %>
<asp:Content ID="Pracownicy" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    Nazwisko pracownika: 
    <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="Id_pracownik" DataValueField="Id_pracownik">
    </asp:DropDownList>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"  SelectCommand="SELECT * FROM [Pracownik] ORDER BY [nazwisko]">
    </asp:SqlDataSource> 
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None" Width="900px" Font-Bold="True" Font-Names="Arial" Font-Size="Medium" HorizontalAlign="Center" EmptyDataText="Brak danych." AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id_pracownik,Id_dzial_stanowisko1,Id_dzial1,Id_stanowisko1,Id_placa1">
        <AlternatingRowStyle BackColor="White" HorizontalAlign="Center" VerticalAlign="Middle" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="Id_pracownik" HeaderText="Id_pracownik" SortExpression="Id_pracownik" InsertVisible="False" ReadOnly="True" Visible="False" />
            <asp:BoundField DataField="Id_dzial_stanowisko" HeaderText="Id_dzial_stanowisko" SortExpression="Id_dzial_stanowisko" Visible="False" />
            <asp:BoundField DataField="Id_placa" HeaderText="Id_placa" SortExpression="Id_placa" Visible="False" />
            <asp:BoundField DataField="imie" HeaderText="Imię" SortExpression="imie" />
            <asp:BoundField DataField="nazwisko" HeaderText="Nazwisko" SortExpression="nazwisko" />
            <asp:BoundField DataField="adres1" HeaderText="Ulica" SortExpression="adres1" />
            <asp:BoundField DataField="adres2" HeaderText="Kod pocztowy" SortExpression="adres2" />
            <asp:BoundField DataField="adres3" HeaderText="Miejscowość" SortExpression="adres3" />
            <asp:BoundField DataField="nr_telefonu" HeaderText="Nr telefonu" SortExpression="nr_telefonu" />
            <asp:BoundField DataField="staz_pracy" HeaderText="staz_pracy" SortExpression="staz_pracy" Visible="False" />
            <asp:BoundField DataField="Id_dzial_stanowisko1" HeaderText="Id_dzial_stanowisko1" SortExpression="Id_dzial_stanowisko1" Visible="False" InsertVisible="False" ReadOnly="True" />
            <asp:BoundField DataField="Id_dzial" HeaderText="Id_dzial" SortExpression="Id_dzial" Visible="False" />
            <asp:BoundField DataField="Id_stanowisko" HeaderText="Id_stanowisko" SortExpression="Id_stanowisko" Visible="False" />
            <asp:BoundField DataField="Id_dzial1" HeaderText="Id_dzial1" SortExpression="Id_dzial1" Visible="False" InsertVisible="False" ReadOnly="True" />
            <asp:BoundField DataField="dzial" HeaderText="Dział" SortExpression="dzial" Visible="False" />
            <asp:BoundField DataField="Id_stanowisko1" HeaderText="Id_stanowisko1" InsertVisible="False" ReadOnly="True" SortExpression="Id_stanowisko1" Visible="False" />
            <asp:BoundField DataField="Stanowisko" HeaderText="Stanowisko" SortExpression="Stanowisko" Visible="False" />
            <asp:BoundField DataField="Id_placa1" HeaderText="Id_placa1" InsertVisible="False" ReadOnly="True" SortExpression="Id_placa1" Visible="False" />
            <asp:BoundField DataField="placa_na_h" HeaderText="Stawka" SortExpression="placa_na_h" />
        </Columns>
        <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" BackColor="#999999" />
        <EmptyDataRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" HorizontalAlign="Center" VerticalAlign="Middle" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle HorizontalAlign="Center" VerticalAlign="Middle" BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>
    <br />
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT Pracownik.*, Dzial_stanowisko.*, Dzial.*, Stanowisko.*, Placa.* FROM Pracownik INNER JOIN Dzial_stanowisko ON Pracownik.Id_dzial_stanowisko = Dzial_stanowisko.Id_dzial_stanowisko INNER JOIN Dzial ON Dzial_stanowisko.Id_dzial = Dzial.Id_dzial INNER JOIN Stanowisko ON Dzial_stanowisko.Id_stanowisko = Stanowisko.Id_stanowisko INNER JOIN Placa ON Pracownik.Id_placa = Placa.Id_placa

WHERE Pracownik.id_pracownik=@nazwisko">
        <SelectParameters>
            <asp:ControlParameter ControlID="DropDownList1" Name="nazwisko" PropertyName="SelectedValue" />
        </SelectParameters>
    </asp:SqlDataSource>
</asp:Content>
